name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: W09 Test
      id: w09-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: W09 Test
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        W09-TEST_RESULTS: "${{steps.w09-test.outputs.result}}"
      with:
        runners: w09-test
